safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

#exclude: [".sass-cache", "Gemfile", "Gemfile.lock"]


future:      true
lsi:         false
pygments:    false
markdown:    redcarpet2
permalink:   date

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
